### ISSUE TITLE
Env::assert_panic_with_status does not catch HostError's containing Status

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#642]

**Comment by leighmcculloch** [comment]
In https://github.com/stellar/rs-soroban-sdk/pull/641 I added use of the `assert_panic_with_status` function which raises a panic containing a `HostError` that contains a `Value` that is `Status`, but the assert function doesn't capture it, for some reason it sees the panic as a `String`.

**Comment by leighmcculloch** [comment]
This test sees the following exception:

https://github.com/stellar/rs-soroban-sdk/blob/6292b9da98ddb8e09cef9b0ac96461cc0e8aa8c3/tests/result/src/lib.rs#L50-L53

```
thread 'test::hello_error' panicked at 'inner function panicked with "called `Result::unwrap()` on an `Err` value: HostError
Value: Status(ContractError(1))

Debug events (newest first):
   0: "Status(ContractError(1))"

Backtrace (newest first):
   0: backtrace::backtrace::libunwind::trace
             at /Users/leighmcculloch/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/leighmcculloch/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/leighmcculloch/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/leighmcculloch/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:176:9
   3: backtrace::capture::Backtrace::new_unresolved
             at /Users/leighmcculloch/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:170:9
   4: <soroban_env_host::host::error::HostError as core::convert::From<T>>::from
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/a1f3a5c/soroban-env-host/src/host/error.rs:113:25
   5: <T as core::convert::Into<U>>::into
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/convert/mod.rs:550:9
   6: soroban_env_host::host::err_helper::<impl soroban_env_host::host::Host>::err
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/a1f3a5c/soroban-env-host/src/host/err_helper.rs:18:37
   7: soroban_env_host::host::err_helper::<impl soroban_env_host::host::Host>::err_status
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/a1f3a5c/soroban-env-host/src/host/err_helper.rs:30:9
   8: soroban_env_host::host::Host::with_frame
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/a1f3a5c/soroban-env-host/src/host.rs:351:25
   9: soroban_env_host::host::Host::call_n
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/a1f3a5c/soroban-env-host/src/host.rs:704:24
  10: <soroban_env_host::host::Host as soroban_env_common::vmcaller_checked_env::VmCallerCheckedEnv>::call
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/a1f3a5c/soroban-env-host/src/host.rs:1708:19
  11: soroban_env_common::vmcaller_checked_env::<impl soroban_env_common::checked_env::CheckedEnv for T>::call
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/a1f3a5c/soroban-env-common/src/vmcaller_checked_env.rs:167:43
  12: soroban_env_common::checked_env::<impl soroban_env_common::env::Env for T>::call
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/a1f3a5c/soroban-env-common/src/checked_env.rs:123:35
  13: <soroban_sdk::env::Env as soroban_env_common::env::Env>::call
             at /Users/leighmcculloch/Code/rs-soroban-sdk/soroban-sdk/src/env.rs:597:13
  14: soroban_sdk::env::Env::invoke_contract
             at /Users/leighmcculloch/Code/rs-soroban-sdk/soroban-sdk/src/env.rs:108:18
  15: example_result::ContractClient::hello
             at src/lib.rs:12:1
  16: example_result::test::hello_error::{{closure}}
             at src/lib.rs:52:21
  17: soroban_sdk::env::Env::clone_self_and_catch_panic::{{closure}}
             at /Users/leighmcculloch/Code/rs-soroban-sdk/soroban-sdk/src/env.rs:435:76
  18: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
  19: std::panicking::try::do_call
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  20: ___rust_try
  21: std::panicking::try
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  22: std::panic::catch_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  23: soroban_sdk::env::Env::clone_self_and_catch_panic
             at /Users/leighmcculloch/Code/rs-soroban-sdk/soroban-sdk/src/env.rs:435:19
  24: soroban_sdk::env::Env::assert_panic_with_status
             at /Users/leighmcculloch/Code/rs-soroban-sdk/soroban-sdk/src/env.rs:467:15
  25: example_result::test::hello_error
             at src/lib.rs:51:9
  26: example_result::test::hello_error::{{closure}}
             at src/lib.rs:44:5
  27: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5

" when status Status(ContractError(1)) expected', /Users/leighmcculloch/Code/rs-soroban-sdk/soroban-sdk/src/env.rs:493:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: soroban_sdk::env::Env::assert_panic_with_status
             at /Users/leighmcculloch/Code/rs-soroban-sdk/soroban-sdk/src/env.rs:493:21
   3: example_result::test::hello_error
             at ./src/lib.rs:51:9
   4: example_result::test::hello_error::{{closure}}
             at ./src/lib.rs:44:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by leighmcculloch** [comment]
That stack trace is pretty long, but the key parts are:
```
inner function panicked with "called `Result::unwrap()` on an `Err` value: HostError
Value: Status(ContractError(1))

Debug events (newest first):
   0: "Status(ContractError(1))"
...
" when status Status(ContractError(1)) expected'
```

It looks like the status we expect is there, it just isn't being extracted.
